#!/bin/bash
PROJECT_DIR="/Users/kamiya/Desktop/kaironishifunabashi/kaironishifunabashi"
BASE_URL="http://www.nishifuna-seitai.jp"

# Absolute URLs in images_mt
curl -L -o "$PROJECT_DIR/images_mt/logo.png" "$BASE_URL/images_mt/logo.png"
curl -L -o "$PROJECT_DIR/images_mt/tel.png" "$BASE_URL/images_mt/tel.png"
curl -L -o "$PROJECT_DIR/images_mt/ashiyase_topimg.jpg" "$BASE_URL/images_mt/ashiyase_topimg.jpg"
curl -L -o "$PROJECT_DIR/images_mt/pagebanner_01_off.gif" "$BASE_URL/images_mt/pagebanner_01_off.gif"
curl -L -o "$PROJECT_DIR/images_mt/pagebanner_02_off.gif" "$BASE_URL/images_mt/pagebanner_02_off.gif"
curl -L -o "$PROJECT_DIR/images_mt/ashiyase_photo01.jpg" "$BASE_URL/images_mt/ashiyase_photo01.jpg"
curl -L -o "$PROJECT_DIR/images_mt/ashiyase_photo02.jpg" "$BASE_URL/images_mt/ashiyase_photo02.jpg"
curl -L -o "$PROJECT_DIR/images_mt/step_arrow.gif" "$BASE_URL/images_mt/step_arrow.gif"
curl -L -o "$PROJECT_DIR/images_mt/btn_voice_mouseout.gif" "$BASE_URL/images_mt/btn_voice_mouseout.gif"
curl -L -o "$PROJECT_DIR/images_mt/ashiyase_photo0609.jpg" "$BASE_URL/images_mt/ashiyase_photo0609.jpg"
curl -L -o "$PROJECT_DIR/images_mt/ashi_img01.jpg" "$BASE_URL/images_mt/ashi_img01.jpg"
curl -L -o "$PROJECT_DIR/images_mt/ashi_tx01.png" "$BASE_URL/images_mt/ashi_tx01.png"
curl -L -o "$PROJECT_DIR/images_mt/ashi_img02.jpg" "$BASE_URL/images_mt/ashi_img02.jpg"
curl -L -o "$PROJECT_DIR/images_mt/ashi_tx02.png" "$BASE_URL/images_mt/ashi_tx02.png"
curl -L -o "$PROJECT_DIR/images_mt/ashi_img03.jpg" "$BASE_URL/images_mt/ashi_img03.jpg"
curl -L -o "$PROJECT_DIR/images_mt/ashi_tx03.png" "$BASE_URL/images_mt/ashi_tx03.png"
curl -L -o "$PROJECT_DIR/images_mt/ashi_img04.jpg" "$BASE_URL/images_mt/ashi_img04.jpg"
curl -L -o "$PROJECT_DIR/images_mt/ashi_tx04.png" "$BASE_URL/images_mt/ashi_tx04.png"
curl -L -o "$PROJECT_DIR/images_mt/ashi_img05.jpg" "$BASE_URL/images_mt/ashi_img05.jpg"
curl -L -o "$PROJECT_DIR/images_mt/ashi_tx05.png" "$BASE_URL/images_mt/ashi_tx05.png"
curl -L -o "$PROJECT_DIR/images_mt/ashi_img06.jpg" "$BASE_URL/images_mt/ashi_img06.jpg"
curl -L -o "$PROJECT_DIR/images_mt/ashi_tx06.png" "$BASE_URL/images_mt/ashi_tx06.png"
curl -L -o "$PROJECT_DIR/images_mt/ashi_img07.jpg" "$BASE_URL/images_mt/ashi_img07.jpg"
curl -L -o "$PROJECT_DIR/images_mt/ashi_tx07.png" "$BASE_URL/images_mt/ashi_tx07.png"
curl -L -o "$PROJECT_DIR/images_mt/side_bn02_mouseout.jpg" "$BASE_URL/images_mt/side_bn02_mouseout.jpg"
curl -L -o "$PROJECT_DIR/images_mt/side_bn03_mouseout.jpg" "$BASE_URL/images_mt/side_bn03_mouseout.jpg"
curl -L -o "$PROJECT_DIR/images_mt/blog_mouseout.png" "$BASE_URL/images_mt/blog_mouseout.png"
curl -L -o "$PROJECT_DIR/images_mt/side_voice_mouseout.png" "$BASE_URL/images_mt/side_voice_mouseout.png"
curl -L -o "$PROJECT_DIR/images_mt/side_qa_mouseout.png" "$BASE_URL/images_mt/side_qa_mouseout.png"
curl -L -o "$PROJECT_DIR/images_mt/seitai nishifuna.jpg" "$BASE_URL/images_mt/seitai%20nishifuna.jpg"
curl -L -o "$PROJECT_DIR/images_mt/nishifuna-para.jpg" "$BASE_URL/images_mt/nishifuna-para.jpg"

# Relative paths in images
curl -L -o "$PROJECT_DIR/images/spacer.gif" "$BASE_URL/images/spacer.gif"
curl -L -o "$PROJECT_DIR/images_mt/arrow01.png" "$BASE_URL/images_mt/arrow01.png"

# Style images
curl -L -o "$PROJECT_DIR/style/00/images/access_title.png" "$BASE_URL/style/00/images/access_title.png"
curl -L -o "$PROJECT_DIR/style/00/images/btn_access_detail.png" "$BASE_URL/style/00/images/btn_access_detail.png"
curl -L -o "$PROJECT_DIR/style/00/images/contact_bg.png" "$BASE_URL/style/00/images/contact_bg.png"
curl -L -o "$PROJECT_DIR/style/00/images/fontsize.png" "$BASE_URL/style/00/images/fontsize.png"
curl -L -o "$PROJECT_DIR/style/00/images/fontsize_btn_l_mouseout.png" "$BASE_URL/style/00/images/fontsize_btn_l_mouseout.png"
curl -L -o "$PROJECT_DIR/style/00/images/fontsize_btn_m_mouseout.png" "$BASE_URL/style/00/images/fontsize_btn_m_mouseout.png"
curl -L -o "$PROJECT_DIR/style/00/images/fontsize_btn_s_mouseout.png" "$BASE_URL/style/00/images/fontsize_btn_s_mouseout.png"
curl -L -o "$PROJECT_DIR/style/00/images/pagetop.png" "$BASE_URL/style/00/images/pagetop.png"

# JS
curl -L -o "$PROJECT_DIR/js/contents.js" "$BASE_URL/js/contents.js"
curl -L -o "$PROJECT_DIR/js/fontSizeChange.js" "$BASE_URL/js/fontSizeChange.js"
curl -L -o "$PROJECT_DIR/js/jquery-1.3.1.min.js" "$BASE_URL/js/jquery-1.3.1.min.js"
curl -L -o "$PROJECT_DIR/js/jquery.cookie.js" "$BASE_URL/js/jquery.cookie.js"
curl -L -o "$PROJECT_DIR/js/jquery.lightbox-0.5.min.js" "$BASE_URL/js/jquery.lightbox-0.5.min.js"
curl -L -o "$PROJECT_DIR/js/menu.js" "$BASE_URL/js/menu.js"
curl -L -o "$PROJECT_DIR/js/smartRollover.js" "$BASE_URL/js/smartRollover.js"
curl -L -o "$PROJECT_DIR/js/DD_belatedPNG_0.0.8a-min.js" "$BASE_URL/js/DD_belatedPNG_0.0.8a-min.js"

# CSS
curl -L -o "$PROJECT_DIR/css/import.css" "$BASE_URL/css/import.css"
curl -L -o "$PROJECT_DIR/css/jquery.lightbox-0.5.css" "$BASE_URL/css/jquery.lightbox-0.5.css"
curl -L -o "$PROJECT_DIR/css/printImport.css" "$BASE_URL/css/printImport.css"
curl -L -o "$PROJECT_DIR/css/common.css" "$BASE_URL/css/common.css"
curl -L -o "$PROJECT_DIR/css/menu.css" "$BASE_URL/css/menu.css"
curl -L -o "$PROJECT_DIR/css/content_o.css" "$BASE_URL/css/content_o.css"
curl -L -o "$PROJECT_DIR/css/content_g.css" "$BASE_URL/css/content_g.css"
curl -L -o "$PROJECT_DIR/style/00/00_base.css" "$BASE_URL/style/00/00_base.css"
curl -L -o "$PROJECT_DIR/style/00/00.css" "$BASE_URL/style/00/00.css"
